PREFIX ex: <https://example.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?subject ?predicate ?object
       ?source_subject ?source_predicate ?source_object ?hide
       ?subject_label ?predicate_label ?object_label
       ?source_subject_label ?source_predicate_label ?source_object_label
WHERE {
  VALUES (?subject ?source_subject ?hide) {
    (ex:France ex:Germany "object")
    (ex:Germany ex:France "subject")
    (ex:Italy ex:Spain "object")
    (ex:Spain ex:Italy "subject")
    (ex:Japan ex:China "object")
    (ex:China ex:Japan "subject")
  }

  ?subject ex:capital ?object ; rdfs:label ?subject_label .
  ?object rdfs:label ?object_label .
  ?source_subject ex:capital ?source_object ; rdfs:label ?source_subject_label .
  ?source_object rdfs:label ?source_object_label .

  BIND(ex:capital AS ?predicate)
  BIND(ex:capital AS ?source_predicate)
  BIND("capital of" AS ?predicate_label)
  BIND("capital of" AS ?source_predicate_label)
}
