PREFIX ex: <https://example.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?entity ?front ?choice ?is_correct
WHERE {
  ?entity ex:capital ?correct_answer ; rdfs:label ?country_name .
  ?choice_resource a ex:City ; rdfs:label ?choice .
  BIND(CONCAT("Capital of ", STR(?country_name), "?") AS ?front)
  BIND(?choice_resource = ?correct_answer AS ?is_correct)
}
